"""change name

Revision ID: 61ad2d5dbd11
Revises: 7dca873fa39b
Create Date: 2025-05-27 23:12:40.413806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ad2d5dbd11'
down_revision: Union[str, None] = '7dca873fa39b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bio_chem', sa.Column('plant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bio_chem', 'plant', ['plant_id'], ['id'])
    op.add_column('plant', sa.Column('place_id', sa.UUID(), nullable=True))
    op.drop_constraint('plant_plant_id_fkey', 'plant', type_='foreignkey')
    op.create_foreign_key(None, 'plant', 'place', ['place_id'], ['id'])
    op.drop_column('plant', 'plant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('plant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'plant', type_='foreignkey')
    op.create_foreign_key('plant_plant_id_fkey', 'plant', 'place', ['plant_id'], ['id'])
    op.drop_column('plant', 'place_id')
    op.drop_constraint(None, 'bio_chem', type_='foreignkey')
    op.drop_column('bio_chem', 'plant_id')
    # ### end Alembic commands ###
