"""m2m research

Revision ID: 7dca873fa39b
Revises: c3ab561d083e
Create Date: 2025-05-23 01:05:07.663132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dca873fa39b'
down_revision: Union[str, None] = 'c3ab561d083e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialist_in_research',
    sa.Column('research_id', sa.UUID(), nullable=True),
    sa.Column('specialist_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['research_id'], ['research.id'], ),
    sa.ForeignKeyConstraint(['specialist_id'], ['specialist.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialist_in_research')
    # ### end Alembic commands ###
